server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
management:
  security:
    enabled: false
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我的自定义元数据
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
