server:
  port: 8003
spring:
  application:
    name: school-front-server-feign
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@192.168.254.142:8861/eureka/,http://admin:admin@192.168.254.143:8861/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  eureka:
    enabled: true

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true