eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-gather-store-service
  security:
    user:
      name: ymjrchx
      password: ymjrchx
management:
  endpoints:
    web:
      exposure:
        include: "*"